### ISSUE TITLE
I still get "undefined is not a function" on fresh meteor 0.6.5 projects

### ISSUE THREAD

**Issue by kjetilge** [apendua/meteor-tags#10] opened 2013-09-14 10:58 UTC
I've now repeated:
meteor create testTags
then..
mrt add tags

then when i run the app i get:

Your app is crashing. Here's the latest log.

W20130914-12:44:50.329(2)? (STDERR) /Users/kjetil/GoogleDrive/meteor-dev (1)/tagsTest/.meteor/local/build/programs/server/boot.js:184
W20130914-12:44:50.332(2)? (STDERR) }).run();
W20130914-12:44:50.332(2)? (STDERR)    ^
W20130914-12:44:50.335(2)? (STDERR) TypeError: undefined is not a function
W20130914-12:44:50.336(2)? (STDERR)     at packages/tags/lib/tags.js:7
W20130914-12:44:50.336(2)? (STDERR)     at packages/tags.js:164:4
W20130914-12:44:50.337(2)? (STDERR)     at packages/tags.js:173:3
W20130914-12:44:50.337(2)? (STDERR)     at mains (/Users/kjetil/GoogleDrive/meteor-dev (1)/tagsTest/.meteor/local/build/programs/server/boot.js:153:10)
W20130914-12:44:50.337(2)? (STDERR)     at Array.forEach (native)
W20130914-12:44:50.337(2)? (STDERR)     at Function._.each._.forEach (/Users/kjetil/.meteor/tools/3cba50c44a/lib/node_modules/underscore/underscore.js:79:11)
W20130914-12:44:50.338(2)? (STDERR)     at /Users/kjetil/GoogleDrive/meteor-dev (1)/tagsTest/.meteor/local/build/programs/server/boot.js:80:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

So there is still something odd going on. 
I'm on Meteorite version 0.6.11
Release 0.6.5.1

**Comment by apendua** [comment] 2013-09-14 23:39
Duplicate of #9.

**Closed as completed by apendua** 2013-09-14 23:39 UTC
Labels: duplicate
